---
language: php

dist: trusty

sudo: true

before_install:
  - sudo apt-get update -qq

  # Remove MySQL. Completely and totally.
  - sudo apt-get -y remove --purge 'mysql*'
  - sudo apt-get -y autoremove
  - sudo apt-get autoclean
  - sudo rm -rf /var/lib/mysql
  - sudo truncate -s 0 /var/log/mysql/error.log

env:
  matrix:
    - DRUSH_DEV=true
    - DRUSH_DEV=false

script:
  - sudo ansible/bootstrap.sh
