---
- hosts: localhost
  vars:
    drush_version: master
  roles:
    - geerlingguy.mysql
    - geerlingguy.drush
  tasks:
    - apt:
        name: "{{ item }}"
        state: installed
      with_items:
        - screen
        - htop
        - strace
        - tree
